### ISSUE TITLE
Webpack Setup

### ISSUE THREAD

**Issue by bastianallgeier** [k-next/website#4]

**Comment by fabianmichael** [comment]
@bastianallgeier  Basic Webpack setup is done for now. So far, everything compiles as is should, I also made PHP dev server available from the CLI, so there’s no need to run MAMP anymore. Just type `npm run server` to start both PHP and Webpack.

The only things I could not get running so far are separate build for template-specific CSS and JS, as this goes beyond my knowledge. But as there is some time left for the relase, we can tackle this later-on. However, If it turns out that we cannot handle it at all due to the nature of how webpack works, we can always go back to a gulp-based build process.

Using webpack also means, that all source files including images are now located in `src/images` to make path resolution easier. Those assets are copied automatically by Webpack, once they’re referenced in a CSS or JS file.  The `www/assets` folder now serves basically as a cache/dist directory.
